// <auto-generated />
using System;
using Cassanello.Web.Datos;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Cassanello.Web.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20200214152132_AgregarTablas")]
    partial class AgregarTablas
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Cassanello.Web.Datos.Entidades.Agenda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date");

                    b.Property<bool>("IsAvailable");

                    b.Property<int?>("MedicoId");

                    b.Property<string>("Remarks");

                    b.Property<int?>("VisitadorId");

                    b.HasKey("Id");

                    b.HasIndex("MedicoId");

                    b.HasIndex("VisitadorId");

                    b.ToTable("Agendas");
                });

            modelBuilder.Entity("Cassanello.Web.Datos.Entidades.Especialidad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(10);

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("Especialidades");
                });

            modelBuilder.Entity("Cassanello.Web.Datos.Entidades.Historico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<int?>("MedicoId");

                    b.Property<string>("Remarks")
                        .HasMaxLength(254);

                    b.HasKey("Id");

                    b.HasIndex("MedicoId");

                    b.ToTable("Historicos");
                });

            modelBuilder.Entity("Cassanello.Web.Datos.Entidades.Laboratorio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(10);

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("Laboratorios");
                });

            modelBuilder.Entity("Cassanello.Web.Datos.Entidades.Medico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Born");

                    b.Property<int?>("EspecialidadId");

                    b.Property<string>("ImageUrl");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("Race")
                        .HasMaxLength(50);

                    b.Property<string>("Remarks")
                        .HasMaxLength(255);

                    b.Property<int?>("VisitadorId");

                    b.HasKey("Id");

                    b.HasIndex("EspecialidadId");

                    b.HasIndex("VisitadorId");

                    b.ToTable("Medicos");
                });

            modelBuilder.Entity("Cassanello.Web.Datos.Entidades.Visitador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CellPhone")
                        .HasMaxLength(20);

                    b.Property<string>("Document")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("Visitadores");
                });

            modelBuilder.Entity("Cassanello.Web.Datos.Entidades.Agenda", b =>
                {
                    b.HasOne("Cassanello.Web.Datos.Entidades.Medico", "Medico")
                        .WithMany()
                        .HasForeignKey("MedicoId");

                    b.HasOne("Cassanello.Web.Datos.Entidades.Visitador", "Visitador")
                        .WithMany("Agendas")
                        .HasForeignKey("VisitadorId");
                });

            modelBuilder.Entity("Cassanello.Web.Datos.Entidades.Historico", b =>
                {
                    b.HasOne("Cassanello.Web.Datos.Entidades.Medico", "Medico")
                        .WithMany("Historicos")
                        .HasForeignKey("MedicoId");
                });

            modelBuilder.Entity("Cassanello.Web.Datos.Entidades.Medico", b =>
                {
                    b.HasOne("Cassanello.Web.Datos.Entidades.Especialidad", "Especialidad")
                        .WithMany("Medicos")
                        .HasForeignKey("EspecialidadId");

                    b.HasOne("Cassanello.Web.Datos.Entidades.Visitador", "Visitador")
                        .WithMany("Medicos")
                        .HasForeignKey("VisitadorId");
                });
#pragma warning restore 612, 618
        }
    }
}
